project_name: git-resume

builds:
  - id: git-resume
    main: ./main.go
    binary: git-resume
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: git-resume
    homepage: "https://github.com/guilhermezuriel/git-resume"
    description: "CLI to summarize git commits using AI"
    repository:
      owner: guilhermezuriel
      name: homebrew-tap

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: guilhermezuriel
    name: git-resume